### PR TITLE
[Backport Foxy] Removed Github Actions (#105)

### PR DESCRIPTION
**Pull request by ahcorde**
Signed-off-by: ahcorde <ahcorde@gmail.com>

### CODE REVIEW

**Review by clalancette — APPROVED** [review]

**Comment by ahcorde** [comment]
@ros-pull-request-builder retest this please

**Comment by mjeronimo** [comment]
@ros-pull-request-builder retest this please

**Review by emersonknapp — APPROVED** [review]

**Comment by emersonknapp** [comment]
@ros-pull-request-builder retest

**Comment by emersonknapp** [comment]
@ros-pull-request-builder retest this please

**Comment by emersonknapp** [comment]
@clalancette do you understand the API/ABI checker issues on the PR builder? It's not something I'm yet familiar with inspecting

**Comment by ahcorde** [comment]
@emersonknapp, 

There is an issue about this here https://github.com/osrf/auto-abi-checker/issues/23 and I proposed a fix in the ABI checker https://github.com/osrf/auto-abi-checker/pull/25

**Review by jacobperron — APPROVED** [review]
I'm okay merging this even though the ABI checker is acting up. Clearly there's no ABI break here.

**Pull request merged**
