### PR TITLE
[backport foxy] Add stream operator for paths to make it easier to log #120

### PR DESCRIPTION
**Pull request by emersonknapp**
https://github.com/ros2/rcpputils/pull/120

### CODE REVIEW

**Review by clalancette — APPROVED** [review]
Looks good to me with green CI.

**Comment by emersonknapp** [comment]
Gist: https://gist.githubusercontent.com/emersonknapp/0c1aa77e318a18e0d45042140c2e4fa0/raw/bfd5604e125ffc070c242c4e7a85f020dea74632/ros2.repos
BUILD args: --packages-up-to rcpputils
TEST args: --packages-select rcpputils
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/7594
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13607/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8489/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11323/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13667/)

**Comment by emersonknapp** [comment]
@ros-pull-request-builder retest this please

**Comment by emersonknapp** [comment]
@clalancette are you able to determine why the PR builder is failed? Do you think we'd be OK to merge this PR?

**Comment by clalancette** [comment]
I'm not totally sure what is going on here, but I know that it definitely shouldn't be running CI for rolling.  Let me close this PR and re-open it to see if that reconfigures the jobs at all.

**Comment by clalancette** [comment]
So, the Rpr job won't run again (since it is configured for a different branch), but it won't remove it from the results.  We can ignore it.

The Lint jobs are all failing because of changes to GitHub actions and `set-env`; I think we can ignore those as well.

I'm not totally sure why the DCO bot is upset, but you may be able to fix it by rebasing this commit on the latest.

Finally, the Fpr job actually did run.  It has a lot of compiler warnings/errors, but all of the tests pass.  I'm not quite sure what to make of that.

All in all, it seems reasonable to me to resolve the DCO problem, and otherwise move forward with this PR based on the test results on https://ci.ros2.org.  But I'll leave final determination of that to @jacobperron

**Comment by emersonknapp** [comment]
> The Lint jobs are all failing because of changes to GitHub actions and set-env;

Yeah this is configuration rot for very old versions of these packages - the `master` branch of `rcpputils` has stopped using these actions, and they probably should be disabled for released distro branches where they won't get version updates, anyways.

> DCO bot is upset

Fixed

> Finally, the Fpr job actually did run. It has a lot of compiler warnings/errors

That's not what I saw - I see 0 warns/errs, at least on the latest run.  But the API/ABI report seems broken.

> move forward with this PR based on the test results on https://ci.ros2.org.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14756/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9506/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12420/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14903/)

**Review by jacobperron — APPROVED** [review]
I'm not sure what's up with the ABI checker. Pinging @j-rivero in case you've experienced this before.

**Comment by jacobperron** [comment]
It would be nice to see a green Windows job before merging. Hopefully it is just an infrastructure flake. Re-running: [Build Status](https://ci.ros2.org/job/ci_windows/14905/)

**Comment by emersonknapp** [comment]
Was indeed an infrastructure flake

**Review by jacobperron — APPROVED** [review]

**Pull request merged**
