### PR TITLE
Adds CODEOWNERS file

### PR DESCRIPTION
**Pull request by thomas-moulard**
Ensures that any two members of the @ros2/dev or @ros2/aws-robotics
teams can approve changes.

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
Does this also trigger review request notifications for these teams which are "participating level" rather than bulk GitHub notifications? In which case you're sending higher priority notifications to a quite large number of individuals who, as far as I know, have no way to opt out of them for this repository.

**Comment by thomas-moulard** [comment]
Ok it's wrong, I'm going to update this PR.

**Comment by thomas-moulard** [comment]
@nuclearsandwich Trying out using a dedicated team for now. We'll see how it goes.

**Comment by thomas-moulard** [comment]
@tfoote @emersonknapp PTAL

**Comment by tfoote** [comment]
I believe the approval gating is related to having commit access. The codeowners is related to notifications/direct requests so I think this works as it it. If you want more reviews they can manually be requested.

**Pull request merged**
