### PR TITLE
[env] Add `set_env_var` function

### LINKED ISSUE #149: Environment helpers: function to set environment variable?
## Feature request

It would be nice to have a way to set environment variables. I have at least one use-case in https://github.com/ros2/domain_bridge/pull/60#discussion_r740617226.

#### Feature description
A function that allows setting a named environment variable; essentially a dual of `rcpputils::get_env_var`.

#### Implementation considerations
It could be implemented exactly how `rcpputils::get_env_var` is implemented, by invoking the corresponding `rcutils` environment helper function.

One approach:
```cpp
bool set_env_var(const char * env_var, const char * env_value)
{
  if (!rcutils_set_env(env_var, env_value)) {
    std::string err = rcutils_get_error_string().str;
    // Resetting the error state since error string has been extracted
    rcutils_reset_error();
    throw std::runtime_error(err);
  }
  return true;
}
```

### PR DESCRIPTION
**Pull request by aprotyas**
This PR adds the `set_env_var` function, which is essentially an `rcpputils` wrapper around `rcutils_set_env`.

I've also renamed `get_env.{hpp,cpp}` to `env.{hpp,cpp}` given the addition of a new method to the "environment helper" functions.

Downstream PRs necessitated by this change:
- [ ] https://github.com/ros2/rcl_logging/pull/81
- [ ] https://github.com/ros2/rmw_implementation/pull/198
- [ ] https://github.com/ros-perception/image_common/pull/211

Closes #149.

Signed-off-by: Abrar Rahman Protyasha <aprotyas@u.rochester.edu>

### CODE REVIEW

**Comment by aprotyas** [comment]
Running CI.
Repos file: https://gist.github.com/aprotyas/96874af9175859555af0144398e0bf25
Build/Test args: `--packages-above-and-dependencies rcpputils`
ROS distro: Rolling
Job: https://ci.ros2.org/job/ci_launcher/9263

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15548/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10232/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/13215/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15760/)

**Comment by aprotyas** [comment]
About the macOS test failures: these have been reported as flaky in https://github.com/ros2/rcl/issues/750, and they don't look related. Oddly, these tests also failed in a CI run for https://github.com/ros2/rcl/pull/946.

About the windows test failures: not sure what's going on. All failing tests seem to be of the "graceful termination" type.

**Comment by aprotyas** [comment]
I just realized that the `get_env.hpp` header file should not be removed outright, but rather be deprecated in a tick-tock cycle, as was done for `rcutils/get_env.h` in https://github.com/ros2/rcutils/pull/340.

Having said that, I've reverted the deletion of `get_env.hpp` and deprecated said header in 18b406b.

**Comment by fujitatomoya** [comment]
Ah, i missed that, sorry. there should be a lifecycle for deprecation.

**Review by fujitatomoya — APPROVED** [review]

**Review by clalancette — APPROVED** [review]

**Comment by aprotyas** [comment]
Running CI again following https://github.com/ros2/rcpputils/pull/150/commits/18b406b24f6728d7d2b04d00c332b9898c86205f.

Repos file: https://gist.github.com/aprotyas/96874af9175859555af0144398e0bf25
Build args: `--packages-above-and-dependencies rcpputils`
Test args: `--packages-above rcpputils`
ROS distro: Rolling
Job: https://ci.ros2.org/job/ci_launcher/9295

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15556/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10240/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/13224/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15770/)

**Comment by aprotyas** [comment]
Two approvals and CI is green, so I'll merge this in. Thanks for the reviews!

**Pull request merged**
