### PR TITLE
[backport Foxy] Removed doxygen warnings (#86)

### PR DESCRIPTION
**Pull request by ahcorde**
Signed-off-by: ahcorde <ahcorde@gmail.com>

### CODE REVIEW

**Comment by dabonnie** [comment]
How can one verify that the warnings are removed?

**Comment by ahcorde** [comment]
I'm working on a linter to check the Doxygen warnings

**Comment by jacobperron** [comment]
I think this PR was meant to target the `foxy` branch, but was merged to `master` instead.

**Comment by ahcorde** [comment]
targeting the right branch https://github.com/ros2/rcpputils/pull/90

**Pull request merged**
