### PR TITLE
Add clamp header

### LINKED ISSUE #84: Adding common math functions
This issue comes from the an issue during ROS2 Control development: https://github.com/ros-controls/ros2_controllers/issues/40

There are some fairly common math operations (in this case [clamp](https://en.cppreference.com/w/cpp/algorithm/clamp)) that are not accessible unless you use C++17 or Boost.

Do you believe these operations have a place in rcpputils? Should I make a `clamp.hpp` header just for it?

### PR DESCRIPTION
**Pull request by v-lopez**
Avoids temporarily avoids using boost or C++17

In the end I did not need to create another library target for this, since all templates. But I've put in the separate directory as discussed.

Fixes #84

### CODE REVIEW

**Comment by Karsten1987** [comment]
This looks good to me, but I guess it deserves a bit more doxygen. It would be great if you could come up with something similar to what is done in other headers, e.g.: https://github.com/ros2/rcpputils/blob/master/include/rcpputils/join.hpp#L30-L39

**Comment by Karsten1987** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11413/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6630/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9357/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11316/)

**Comment by emersonknapp** [comment]
That is my only feedback as well, to more thoroughly document the functions provided. Thanks for this contribution!

**Comment by v-lopez** [comment]
Sure, I'll do it tomorrow morning.

**Comment by emersonknapp** [comment]
Also note that you will need to use `git commit --signoff` to pass the DCO check. You can do this for existing commits with `git rebase --signoff -i origin/master` and leaving all the commits as `pick`

**Comment by v-lopez** [comment]
I've addressed the documentation and signing, please take a look when you have time.

**Comment by emersonknapp** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11443/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6657/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9386/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11345/)

**Comment by Karsten1987** [comment]
@emersonknapp can this be merged? Ideally we'd like to have this backported to Foxy as well to have ros_control still be compatible with Foxy.

**Comment by wjwwood** [comment]
Uh, I just saw this in the `include` folder. What's the rationale for putting this in a different namespace from `rcpputils`?

We have a pretty consistent pattern of having the root cpp namespaces (and include namespace to match) be the same as the package name.

In my opinion, this should be moved into the `rcpputils` namespace.

**Comment by v-lopez** [comment]
It was done in a separate namespace after discussion in #84, in case in the future similar functions are added and this ends up on a separate package or structure.

**Comment by wjwwood** [comment]
I see, thanks for the pointer @v-lopez, but I have to really disagree with the direction. I think it should be in the `rcpputils` namespace until it is split into a separate package. Splitting it preemptively is just confusing to me. 

I'll probably make pull requests to move it in rolling and deprecate it and provide the new location in foxy, unless someone convinces me otherwise. @emersonknapp @clalancette?

**Comment by clalancette** [comment]
> I'll probably make pull requests to move it in rolling and deprecate it and provide the new location in foxy, unless someone convinces me otherwise. @emersonknapp @clalancette?

That sounds good to me.

**Pull request merged**
