### PR TITLE
create_directories returns true if the path is empty

### PR DESCRIPTION
**Pull request by fujitatomoya**
fix https://github.com/ros2/rcpputils/issues/94, and address https://github.com/ros2/rcpputils/pull/96

### CODE REVIEW

**Comment by fujitatomoya** [comment]
@wjwwood @christophebedard 

I've added minor fix based on https://github.com/ros2/rcpputils/pull/95.

confirmed rosbag2 test does not detects any failures.

**Comment by christophebedard** [comment]
thank you @fujitatomoya!

**Review by clalancette — CHANGES_REQUESTED** [review]
The problem I have with this change is that this makes us act different than `std::filesystem` (which we eventually want to switch to).  As far as I can tell, if you call:

```
std::filesystem::create_directories("");
```

It throws an exception:
```
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: cannot create directories: Invalid argument []
```

Also, from a pure semantic point-of-view, the documentation says that it returns true if the directory is created, and false otherwise.  Since it could not create the directory on an empty string, returning true seems wrong here.

My suggestion is that we actually fix the test in rosbag2 that is trying to call this API with an empty string.  Once that is done, we can reapply #95 as it was, and then things shouldn't break on the farm.

**Comment by christophebedard** [comment]
That makes sense. I can do that (@fujitatomoya let me know if you've started working on it).

**Comment by christophebedard** [comment]
> My suggestion is that we actually fix the test in rosbag2 that is trying to call this API with an empty string. Once that is done, we can reapply #95 as it was, and then things shouldn't break on the farm.

I opened https://github.com/ros2/rosbag2/pull/526

**Comment by fujitatomoya** [comment]
@christophebedard @clalancette 

i will close this PR, you can revert https://github.com/ros2/rcpputils/pull/96 after https://github.com/ros2/rosbag2/pull/526.

**Pull request closed without merging**
