### PR TITLE
replace custom get env logic into rcutils_get_env().

### PR DESCRIPTION
**Pull request by fujitatomoya**
rcpputils fix addresses https://github.com/ros2/ros2/issues/856

Signed-off-by: Tomoya.Fujita <Tomoya.Fujita@sony.com>

### CODE REVIEW

**Review by dirk-thomas — APPROVED** [review]

**Review by emersonknapp — APPROVED** [review]

**Comment by fujitatomoya** [comment]
@clalancette friendly ping!

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12713/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7674/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10427/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12660/)

**Comment by clalancette** [comment]
Hm, all CI builds were yellow.  I suspect that it doesn't have to do with this PR, but nightly is green.  I'm going to relaunch Linux only and see if that was a temporary failure:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12737/)

**Comment by fujitatomoya** [comment]
@clalancette 

let me check the result, will get back to you.

**Comment by fujitatomoya** [comment]
- [test_logging_interface](https://ci.ros2.org/job/ci_linux/12737/testReport/(root)/projectroot/test_logging_interface/)
  - ***Not related***, Nobody even calls `temp_directory_path`.
- [test_sequential_compression_writer](https://ci.ros2.org/job/ci_linux/12737/testReport/junit/(root)/projectroot/test_sequential_compression_writer/)
  - ***Not related***, open_throws_on_empty_storage_options_uri does not use `temp_directory_path`.

I believe that this commit https://github.com/ros2/rcpputils/commit/197357760a89762e1c704681123d1bd425b8f2b1 got something to do with these failures.

I just rebased PR aligned with upstream/master. could you kindly try CI once again?

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12765/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7724/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10474/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12707/)

**Comment by fujitatomoya** [comment]
@clalancette 

some windows tests are flaky,

[rcl action test_graph__rmw_connext_cpp](https://ci.ros2.org/job/ci_windows/12707/testReport/junit/(root)/projectroot/test_graph__rmw_connext_cpp/), ***Not related*** to the PR. because the fix is in `rcpputils`.

**Comment by clalancette** [comment]
@fujitatomoya Yep, I agree with you; in 2 of the last 3 nights, those tests failed.  So I'm going to go ahead and merge this one.  Thanks for iterating.

**Pull request merged**
